name: API Cron Job

on:
  schedule:
    # Runs every hour (customize with cron syntax)
    - cron: "*/2 * * * *"
  # workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          # Use curl or a script to call your API
          curl -X GET "https://sistema-prod.vercel.app/api/reminders"
       
