name: API Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          date # Add date logging
          curl -X GET "https://sistema-prod.vercel.app/api/reminders"
